### ISSUE TITLE
Map out user & data flow

### ISSUE THREAD

**Issue by rrabinovitch** [rrabinovitch/Crate#10]
We'll get together to discuss and map out the user flow on jamboard or miro

**Comment by tarynmartin** [comment]
Included screenshots of user flow and data flow
<img width="632" alt="Screen Shot 2020-10-11 at 2 05 39 PM" src="https://user-images.githubusercontent.com/18726699/95688974-1bf15700-0bcb-11eb-87f3-8b47fe7678bd.png">
<img width="549" alt="Screen Shot 2020-10-11 at 2 06 20 PM" src="https://user-images.githubusercontent.com/18726699/95688980-1eec4780-0bcb-11eb-8193-e660e096d9a9.png">
